name: Run Python App

on:
  push:

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Download code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flask
        run: pip install flask

      if __name__ == "__main__":
    print("App werkt")
